lines = [
"import pandas as pd",
"import numpy as np",
"import plotly.express as px",
"import matplotlib.pyplot as plt",
"import os",
"import re",
"import requests",
"import io",
"from sklearn.model_selection import train_test_split",
"from sklearn.linear_model import LinearRegression",
"from sklearn.tree import DecisionTreeRegressor",
"from sklearn.metrics import mean_squared_error, r2_score",
"import google.generativeai as genai",
"from dotenv import load_dotenv",
"",
"# Load environment variables",
"load_dotenv()",
"GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')",
"if GEMINI_API_KEY:",
"    genai.configure(api_key=GEMINI_API_KEY)",
"",
"class DataAnalyst:",
"    def __init__(self):",
"        self.df = None",
"        self.filtered_df = None",
"        self.num_cols = []",
"        self.all_cols = []",
"        self.ml_results = {}",
"        self.model = genai.GenerativeModel('gemini-2.0-flash') if GEMINI_API_KEY else None",
"",
"    def load_data(self, file_path):",
"        try:",
"            if file_path.endswith('.csv'):",
"                self.df = pd.read_csv(file_path, low_memory=False)",
"            else:",
"                self.df = pd.read_excel(file_path)",
"            ",
"            self.clean_data()",
"            ",
"            self.filtered_df = self.df.copy()",
"            self.num_cols = self.df.select_dtypes(include=np.number).columns.tolist()",
"            self.all_cols = self.df.columns.tolist()",
"            print(f'Data loaded: {len(self.df)} rows, {len(self.df.columns)} columns.')",
"            ",
"            preview_df = self.df.head(20).copy()",
"            preview_df = preview_df.where(pd.notnull(preview_df), None)",
"            return preview_df.to_dict(orient='records')",
"        except Exception as e:",
"            print(f'Load Error: {str(e)}')",
"            raise e",
"",
"    def clean_data(self):",
"        if self.df is None: return",
"",
"        for col in self.df.columns:",
"            if not pd.api.types.is_numeric_dtype(self.df[col]):",
"                try:",
"                    cleaned = self.df[col].astype(str).str.strip().str.replace(r'[$,]', '', regex=True)",
"                    cleaned = cleaned.replace('', np.nan)",
"                    converted = pd.to_numeric(cleaned, errors='coerce')",
"                    if converted.notna().sum() > 0:",
"                         self.df[col] = converted",
"                except:",
"                    pass",
"",
"            if pd.api.types.is_numeric_dtype(self.df[col]):",
"                median_val = self.df[col].median()",
"                if pd.notna(median_val):",
"                    self.df[col] = self.df[col].fillna(median_val)",
"                else:",
"                    self.df[col] = self.df[col].fillna(0)",
"            else:",
"                self.df[col] = self.df[col].fillna('Unknown')",
"",
"",
"    def get_real_col(self, target_col):",
"        if self.df is None: return None",
"        for actual_col in self.df.columns:",
"            if actual_col.lower() == target_col.lower():",
"                return actual_col",
"        return None",
"",
"    def apply_ai_filter(self, query):",
"        if self.df is None:",
"            if not self.recover_state():",
"                return '❌ Load dataset first (state lost)'",
"        ",
"        self.filtered_df = self.df.copy()",
"        q = query.lower()",
"        try:",
"            if any(term in q for term in ['remove missing', 'drop missing', 'clean']):",
"                self.filtered_df = self.filtered_df.dropna()",
"            ",
"            patterns = [",
"                (r'([\w\s]+?)\s*(?:is\s+)?(?:more\s+than|>|greater\s+than)\s*(\d+\.?\d*)', '>'),",
"                (r'([\w\s]+?)\s*(?:is\s+)?(?:less\s+than|<|smaller\s+than)\s*(\d+\.?\d*)', '<'),",
"                (r'([\w\s]+?)\s*(?:is\s+)?(?:equal\s+to|=)\s*(\d+\.?\d*)', '=='),",
"            ]",
"",
"            for pattern, op in patterns:",
"                match = re.search(pattern, q)",
"                if match:",
"                    col_name, val = match.groups()",
"                    actual_col = self.get_real_col(col_name.strip())",
"                    if actual_col:",
"                        if op == '>': self.filtered_df = self.filtered_df[self.filtered_df[actual_col] > float(val)]",
"                        elif op == '<': self.filtered_df = self.filtered_df[self.filtered_df[actual_col] < float(val)]",
"                        elif op == '==': self.filtered_df = self.filtered_df[self.filtered_df[actual_col] == float(val)]",
"",
"            return self.filtered_df.head(10).to_dict(orient='records')",
"        except Exception as e:",
"            return f'❌ Error interpreting query: {str(e)}'",
"",
"    def generate_ml_description(self, target, r2, mse):",
"        if r2 > 0.8:",
"            perf = 'excellent. The model explains most of the variation in the data.'",
"        elif r2 > 0.5:",
"            perf = 'good. The model has found a significant relationship but there is room for improvement.'",
"        else:",
"            perf = 'relatively low. This suggests the selected features might not be strong predictors for the target column.'",
"        ",
"        return (f'The analysis predicted {target} using the remaining numerical columns. '",
"                f'The model accuracy (R-squared) is {r2:.2f}, which is considered {perf} '",
"                f'On average, the predictions deviate from actual values by {np.sqrt(mse):.2f} units.')",
"",
"    def run_ml(self, target_col):",
"        if self.df is None:",
"            if not self.recover_state():",
"                return {'error': '❌ No data loaded.'}",
"        ",
"        if self.filtered_df is None:",
"            self.filtered_df = self.df.copy()",
"        ",
"        if not target_col:",
"            return {'error': '❌ Please select a target column.'}",
"        ",
"        if target_col not in self.num_cols:",
"            return {'error': f'❌ {target_col} is not a numeric column.'}",
"        ",
"        if len(self.num_cols) < 2:",
"            return {'error': '❌ Need at least 2 numeric columns for ML.'}",
"        ",
"        try:",
"            data = self.filtered_df.dropna()",
"            if len(data) < 10:",
"                return {'error': f'❌ Insufficient data ({len(data)} rows).'}",
"            ",
"            X = data[self.num_cols].drop(columns=[target_col])",
"            y = data[target_col]",
"            ",
"            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)",
"            model = LinearRegression()",
"            model.fit(X_train, y_train)",
"            preds = model.predict(X_test)",
"            r2 = r2_score(y_test, preds)",
"            mse = mean_squared_error(y_test, preds)",
"            ",
"            plot_data = []",
"            indices = np.random.choice(len(y_test), min(100, len(y_test)), replace=False) if len(y_test) > 100 else range(len(y_test))",
"            y_test_list = y_test.tolist()",
"            preds_list = preds.tolist()",
"            ",
"            for idx in indices:",
"                plot_data.append({'actual': float(y_test_list[idx]), 'predicted': float(preds_list[idx])})",
"",
"            importance = ''",
"            if hasattr(model, 'coef_'):",
"                feat_imp = pd.Series(model.coef_, index=X.columns).abs().sort_values(ascending=False)",
"                top_feats = feat_imp.head(3).index.tolist()",
"                importance = f'Key drivers: {', '.join(top_feats)}. {top_feats[0]} is the top predictor.'",
"",
"            self.ml_results = {",
"                'r2': float(r2),",
"                'mse': float(mse),",
"                'model': 'Linear Regression',",
"                'description': self.generate_ml_description(target_col, r2, mse),",
"                'plot_data': plot_data,",
"                'decision_adviser': importance",
"            }",
"            return self.ml_results",
"        except Exception as e:",
"            return {'error': f'❌ ML failed: {str(e)}'}",
"",
"    def analyze_chart_with_ai(self, chart_type, x_col, y_col, data):",
"        if not self.model: return None",
"        try:",
"            data_summary = data[:10] if isinstance(data, list) else []",
"            prompt = (",
"                f'Analyze this {chart_type} chart. X-axis: {x_col}, Y-axis: {y_col if y_col else \"Frequency\"}. '",
"                f'Sample Data: {data_summary}. Concise 1-2 sentence business insight. No markdown.'",
"            )",
"            response = self.model.generate_content(prompt)",
"            return response.text.strip()",
"        except: return None",
"",
"    def get_auto_charts(self):",
"        if self.df is None: self.recover_state()",
"        if self.df is None: return []",
"        ",
"        source_df = self.filtered_df if self.filtered_df is not None else self.df",
"        recommendations = []",
"        cols = source_df.columns.tolist()",
"        num_cols = source_df.select_dtypes(include=np.number).columns.tolist()",
"        cat_cols = [c for c in cols if c not in num_cols]",
"",
"        if num_cols:",
"            col = num_cols[0]",
"            counts, bins = np.histogram(source_df[col].dropna(), bins=20)",
"            data = [{'name': f'{bins[i]:.1f}-{bins[i+1]:.1f}', 'value': int(counts[i])} for i in range(len(counts))]",
"            recommendations.append({",
"                'type': 'Histogram', 'x': str(col), 'data': data,",
"                'reason': self.analyze_chart_with_ai('Histogram', col, None, data) or f'Frequency distribution of {col}.'",
"            })",
"        ",
"        if len(num_cols) >= 2:",
"            x_col, y_col = num_cols[0], num_cols[1]",
"            sample_df = source_df.dropna(subset=[x_col, y_col])",
"            scatter_df = sample_df.sample(min(100, len(sample_df)))",
"            data = [{str(x_col): float(row[x_col]), str(y_col): float(row[y_col])} for _, row in scatter_df.iterrows()]",
"            recommendations.append({",
"                'type': 'Scatter', 'x': str(x_col), 'y': str(y_col), 'data': data,",
"                'reason': self.analyze_chart_with_ai('Scatter', x_col, y_col, data) or f'Correlation between {x_col} and {y_col}.'",
"            })",
"            ",
"            line_df = sample_df.sort_values(by=x_col).head(100)",
"            data = [{str(x_col): float(row[x_col]), str(y_col): float(row[y_col])} for _, row in line_df.iterrows()]",
"            recommendations.append({",
"                'type': 'Line', 'x': str(x_col), 'y': str(y_col), 'data': data,",
"                'reason': self.analyze_chart_with_ai('Line', x_col, y_col, data) or f'Trend of {y_col} across {x_col}.'",
"            })",
"",
"        for col in cat_cols[:2]:",
"            counts = source_df[col].value_counts().head(8)",
"            if not counts.empty:",
"                data = [{'name': str(name), 'value': int(val)} for name, val in counts.items()]",
"                recommendations.append({",
"                    'type': 'Pie', 'x': str(col), 'data': data,",
"                    'reason': self.analyze_chart_with_ai('Pie', col, None, data) or f'Category distribution for {col}.'",
"                })",
"",
"        if len(num_cols) >= 2:",
"            h_cols = num_cols[:10]",
"            corr = source_df[h_cols].corr().round(2)",
"            data = []",
"            for i, row_name in enumerate(corr.index):",
"                for j, col_name in enumerate(corr.columns):",
"                    data.append({'x': str(row_name), 'y': str(col_name), 'value': float(corr.iloc[i, j])})",
"            recommendations.append({",
"                'type': 'Heatmap', 'data': data, 'columns': h_cols,",
"                'reason': self.analyze_chart_with_ai('Heatmap Matrix', 'Metrics', None, data) or 'Relationship matrix.'",
"            })",
"",
"        if cat_cols and num_cols:",
"            cat_col, val_col = cat_cols[0], num_cols[0]",
"            grouped = source_df.groupby(cat_col)[val_col].mean().sort_values(ascending=False).head(10).reset_index()",
"            data = [{'name': str(row[cat_col]), 'value': float(row[val_col])} for _, row in grouped.iterrows()]",
"            recommendations.append({",
"                'type': 'Bar', 'x': str(cat_col), 'y': str(val_col), 'data': data,",
"                'reason': self.analyze_chart_with_ai('Bar', cat_col, val_col, data) or f'Average {val_col} by {cat_col}.'",
"            })",
"            ",
"        return recommendations",
"",
"    def recover_state(self):",
"        if not os.path.exists('uploads'): return False",
"        files = [f for f in os.listdir('uploads') if f.endswith(('.csv', '.xlsx', '.xls'))]",
"        if not files: return False",
"        latest_file = max([os.path.join('uploads', f) for f in files], key=os.path.getmtime)",
"        try:",
"            self.load_data(latest_file)",
"            return True",
"        except: return False",
]

with open('processing.py', 'w', encoding='utf-8') as f:
    f.write('\\n'.join(lines))
print('Write Complete')
